name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: jmespath
        run: |
          sudo pip3 install ansible jmespath

      - name: Ansible
        run: |
          ansible-playbook --version
          ansible-playbook -vvv -i hosts site.yml
