name: integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Dependencies
        run: |
          sudo pip uninstall ansible
          sudo pip3 install ansible jmespath

      - name: Extra
        run: |
          ansible-playbook --version
          ansible-config dump --only-changed

      - name: Ansible
        run: |
          ansible-playbook -vvv -i hosts site.yml
